site_name: ViroConstrictor
repo_name: RIVM-bioinformatics/ViroConstrictor
repo_url: https://github.com/RIVM-bioinformatics/ViroConstrictor
copyright: Copyright © 2021 RIVM
edit_uri: ""

# Navigation menu
nav:
  - Home: index.md
  - Getting started:
    - Download & installation: installation.md
    - Global configuration: global-config.md
  - Usage: 
    - manual.md
    - Formatting inputs: input-formatting.md
    - Working with analysis presets: presets.md
    - Explanation of amplicon types: amplicons.md
    - Working with multiple references: multi-reference.md

  - Changelog: changelog.md

# Basic config theming config settings
theme:
  name: material
  language: en
  icon:
    logo: material/dna

# Config settings directly related to the theme itself
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      #- toc.integrate
      - navigation.top
      - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch light mode
  font:
      text: Roboto
      code: Roboto Mono
  plugins:
      - search
      - awesome-pages

# Markdown extensions used by the material-theme
markdown_extensions:
    - meta
    - markdown.extensions.admonition
    - markdown.extensions.attr_list
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # - pymdownx.highlight:
    #     linenums_style: pymdownx-inline
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        social_url_shorthand: true
        user: RIVM-bioinformatics
        repo: ViroConstrictor
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde


# version provider integrated with Material theme
extra:
  version:
    provider: mike