"""Define package and hashing schema version constants."""

from pathlib import Path

VERSION = "0.1.0"
HASH_SCHEMA_VERSION = "v1"
REPO_ROOT = Path(__file__).resolve().parents[2]

CONTAINER_MANAGER_DIR = REPO_ROOT / "container_manager"
CONTAINER_MANAGER_DATA_DIR = CONTAINER_MANAGER_DIR / "data"
CONTAINER_MANAGER_BASE_DATA_DIR = CONTAINER_MANAGER_DATA_DIR / "base_data"

CONTAINER_MANAGER_CONFIG_PATH = CONTAINER_MANAGER_DIR / "config_dockerfiles.yaml"
CONTAINER_MANAGER_TEMPLATE_PATH = CONTAINER_MANAGER_DIR / "docker_template_specific.j2"

CONTAINER_MANAGER_DOCKERFILES_DIR = CONTAINER_MANAGER_DATA_DIR / "dockerfiles"
CONTAINER_MANAGER_CONTAINERS_DIR = CONTAINER_MANAGER_DATA_DIR / "containers"
CONTAINER_MANAGER_MANIFESTS_DIR = CONTAINER_MANAGER_DATA_DIR / "manifests"
CONTAINER_MANAGER_DEFAULT_MANIFEST_PATH = CONTAINER_MANAGER_MANIFESTS_DIR / "container-build-manifest.json"

CONTAINER_MANAGER_BASE_DOCKERFILE_CONFIG_PATH = CONTAINER_MANAGER_BASE_DATA_DIR / "base_dockerfile_config.yaml"

WORKFLOW_ENVS_DIR = REPO_ROOT / "envs"

CONTAINER_MANAGER_MERGE_INPUT_GLOB = "./artifacts/container-build-manifest-*.json"
