name: build containers and run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    

jobs:
  Setup_and_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - Alignment
          - Clean
          - Consensus
          - ORF_analysis
          - core_scripts
          - mr_scripts
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true

      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          post-cleanup: 'all'
          environment-file: env.yml
          init-shell: bash
      
      - name: Install local python package
        run: |
          pip install . --no-deps
        shell: micromamba-shell {0}

      - name: generate container dockerfiles
        run: |
          python -m container_manager generate
        shell: micromamba-shell {0}

      - name: build container
        run: |
          python -m container_manager build --only ${{ matrix.container }} --manifest ./container_manager/data/manifests/container-build-manifest-${{ matrix.container }}.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: micromamba-shell {0}

      - name: pack container artifact
        run: |
          mkdir -p ./artifacts/${{ matrix.container }}
          cp ./container_manager/data/manifests/container-build-manifest-${{ matrix.container }}.json ./artifacts/${{ matrix.container }}/
          cp ./container_manager/data/containers/*.tar ./artifacts/${{ matrix.container }}/


      - name: Upload container artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built_container_${{ matrix.container }}
          path: ./artifacts/${{ matrix.container }}/
          overwrite: true
  
  Test:
    runs-on: ubuntu-latest
    needs: Setup_and_build
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true

      - uses: actions/download-artifact@v4
        with:
          pattern: built_container_*
          path: ./artifacts
          merge-multiple: true

      - name: stage container artifacts
        run: |
          mkdir -p ./container_manager/data/containers
          cp ./artifacts/*.tar ./container_manager/data/containers/
          cat ./artifacts/container-build-manifest-*.json > /dev/null
          python -m container_manager merge-manifests

      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@4bb22c52d4f63406c49e94c804632975787312b3

      - name: Setup Mamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476
        with:
          cache-environment: true
          post-cleanup: 'all'
          environment-file: env.yml
          init-shell: bash
      
      - name: Install local python package
        run: |
          pip install . --no-deps
        shell: micromamba-shell {0}

      - name: convert containers
        run: |
          python -m container_manager convert --manifest ./container_manager/data/manifests/container-build-manifest.json
        shell: micromamba-shell {0}

      - name: download existing containers
        run: |
          mkdir -p ./test_containers
          mv ./container_manager/data/containers/*.sif ./test_containers/ || true
          python -m container_manager sync-cache --cache-dir ./test_containers
        shell: micromamba-shell {0}
      